package homework6;

public enum DogBreed {
    LABRADOR_RETRIEVERS,
    FRENCH_BULLDOG,
    GERMAN_SHEPHERD,
    GOLDEN_RETRIEVER,
    BULLDOG,
    POODLE,
    BEAGLE,
    ROTTWEILER,
    DACHSHUNDS,
    LLASA_APSO
}
